[package]
name = "hnsw"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
bincode2 = "2.0.1"
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
pq = { path = "pq" }
rayon = "1.12.0"

[workspace]
members = ["crates/bench"]

[profile.release]
debug = true
split-debuginfo = "packed"
