[package]
name = "hnsw"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.88"

[dependencies]
bincode2 = "2.0.1"
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
pq = { package = "hnsw-pq", path = "crates/pq", version = "0.1.0" }
rayon = "1.12.0"

[workspace]
members = ["crates/bench", "crates/pq"]

[profile.release]
debug = true
split-debuginfo = "packed"
